subscribers:
  - name:     "joy"
    topic:    "/joy_teleop/cmd_vel"
    timeout:  0.5
    priority: 10

  - name:     "keyboard"
    topic:    "/key_teleop/cmd_vel"
    timeout:  0.5
    priority: 2

  - name:     "web_ui"
    topic:    "/web_app/cmd_vel"
    timeout:  0.5
    priority: 8

  - name:     "autonomy"
    topic:    "/platform_control/cmd_vel"
    timeout:  0.5
    priority: 7

  - name:     "interactive_marker"
    topic:    "/twist_marker_server/cmd_vel"
    timeout:  0.5
    priority: 6

  - name:     "external"
    topic:    "/cmd_vel"
    timeout:  0.5
    priority: 1

publisher:    "/rover_velocity_controller/cmd_vel"
