<?xml version="1.0"?>
<!--
Software License Agreement (BSD)

\file      rover.urdf.xacro
\authors   Wil Selby <wil@wilselby.com>
\copyright Copyright (c) 2017, All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that
the following conditions are met:
 * Redistributions of source code must retain the above copyright notice, this list of conditions and the
   following disclaimer.
 * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the
   following disclaimer in the documentation and/or other materials provided with the distribution.
 * The name of the contributors may not be used to endorse or promote products derived from this software 
   without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WAR-
RANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, IN-
DIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT
OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
-->

<robot name="rover_robot" xmlns:xacro="http://ros.org/wiki/xacro">

  <!-- Included URDF/XACRO Files -->
  <xacro:include filename="$(find rover_description)/urdf/decorations.urdf.xacro" />
  <xacro:include filename="$(find rover_description)/urdf/wheel.urdf.xacro" />
  <xacro:include filename="$(find rover_description)/urdf/accessories/kinect_camera.urdf.xacro"/>
  <xacro:include filename="$(find rover_description)/urdf/accessories/sensor_arch.urdf.xacro"/>
  <xacro:include filename="$(find rover_description)/urdf/accessories/camera.urdf.xacro"/>
  <xacro:include filename="$(find ouster_description)/urdf/OS1-64.urdf.xacro"/>

  <property name="M_PI" value="3.14159"/>

  <!-- Base Size -->
  <property name="base_x_size" value="0.1250000" />
  <property name="base_y_size" value="0.0830000" />
  <property name="base_z_size" value="0.0880000" />

  <!-- Wheel Mounting Positions -->
  <xacro:property name="wheelbase" value="0.10500" />
  <xacro:property name="track" value="0.1315" />
  <xacro:property name="wheel_vertical_offset" value="0.0" />

  <!-- Wheel Properties -->
  <xacro:property name="wheel_length" value="0.042" />
  <xacro:property name="wheel_radius" value="0.044" />

  <xacro:macro name="rover_robot">

    <!-- Base link is the center of the robot's bottom plate -->
    <link name="base_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0" />
        <geometry>
          <mesh filename="package://rover_description/meshes/base_link.dae" scale=".215 .2 .1"  />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 0 ${base_z_size/4}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size} ${base_y_size} ${base_z_size/2}"/>
        </geometry>
      </collision>
      <collision>
        <origin xyz="0 0 ${base_z_size*3/4}" rpy="0 0 0" />
        <geometry>
          <box size="${base_x_size*4/5} ${base_y_size} ${base_z_size/2}"/>
        </geometry>
      </collision>
    </link>

    <!-- Base footprint is on the ground under the robot -->
    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
      <origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="base_footprint" />
    </joint>

    <!-- Interial link stores the robot's inertial information -->
    <link name="inertial_link">
      <inertial>
        <mass value="33.455" /> <!-- TODO: Update -->
        <origin xyz="0.0 0.000 0.0" /> <!-- TODO: Update -->
        <inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" /> <!-- TODO: Update -->
      </inertial>
    </link>

    <joint name="inertial_joint" type="fixed">
      <origin xyz="0 0 0" rpy="0 0 0" />
      <parent link="base_link" />
      <child link="inertial_link" />
    </joint>

    <!-- IMU Link is the standard mounting position for the UM6 IMU.-->
    <!-- Can be modified with environment variables in /etc/ros/setup.bash -->
    <link name="imu_link"/>
    <joint name="imu_joint" type="fixed">
      <!-- <origin xyz="$(optenv HUSKY_IMU_XYZ 0.19 0 0.149)" rpy="$(optenv HUSKY_IMU_RPY 0 -1.5708 3.1416)" /> -->
      <origin xyz="0.19 0 0.149" rpy="0 0 0" />
      <!-- <origin xyz="0.19 0 0.149" rpy="0 -1.5708 3.1416" /> -->
      <parent link="base_link" />
      <child link="imu_link" />
    </joint>
    <gazebo reference="imu_link">
    </gazebo>

    <!-- GPS link -->
    <link name="navsat_link"/>
    <joint name="navsat_joint" type="fixed">
      <parent link="base_link" />
      <child link="navsat_link" />
      <origin xyz="0.19 0 0.149" rpy="0 0 0" />
      <!-- <origin xyz="0.19 0 0.149" rpy="0 -1.5708 3.1416" /> -->
    </joint>
    <gazebo reference="navsat_link">
    </gazebo>

    <!-- Wheel macros -->
    <xacro:rover_wheel wheel_prefix="front_left">
      <origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:rover_wheel>
    <xacro:rover_wheel wheel_prefix="front_right">
      <origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:rover_wheel>
    <xacro:rover_wheel wheel_prefix="rear_left">
      <origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:rover_wheel>
    <xacro:rover_wheel wheel_prefix="rear_right">
      <origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
    </xacro:rover_wheel>


   <xacro:rover_decorate /> 

    <!-- Mount a Kinect Sensor -->
    <xacro:if value="$(arg kinect_enabled)">
      <xacro:sensor_arch prefix="" parent="top_plate_link">
        <origin xyz="-0.35 0 0.51" rpy="0 0 -3.14"/>
      </xacro:sensor_arch>
      <joint name="kinect_frame_joint" type="fixed">
        <!-- <origin xyz="$(optenv HUSKY_KINECT_XYZ 0 0 0)" rpy="$(optenv HUSKY_KINECT_RPY 0 0.18 3.14)" /> -->
  <origin xyz="0 0 0" rpy="0 0.18 3.14" />
        <parent link="sensor_arch_mount_link"/>
        <child link="camera_link"/>
      </joint>

      <xacro:kinect_camera prefix="camera"/>
    </xacro:if>

  <!--Mount a basic camera ${namespace}-->
  <xacro:if value="$(arg camera_enabled)">      
    <xacro:camera_macro
      namespace="raspicam_node"
      parent_link="top_plate_link"
      camera_suffix=""
      frame_rate="30"
      horizontal_fov="2"
      image_width="1280"
      image_height="720"
      image_format="R8G8B8"
      min_distance="0.02"
      max_distance="300"
      noise_mean="0.0"
      noise_stddev="0.007"
      enable_visual="true"
    >
      <box size="0.02 0.02 0.02" />
       <origin xyz="0.062 0.0 0.01" rpy="0 0 0" />
    </xacro:camera_macro>
  </xacro:if>

  <!--Mount a OS1-64-->
  <xacro:if value="$(arg os1-64_enabled)">      
    <xacro:OS1-64
      parent="base_link"
      name="ouster"
      topic="/points"
      hz="10"
      samples="220"
    >
    <origin xyz="0 0 0.02" rpy="0 0 0" />
    </xacro:OS1-64>
  </xacro:if>


  </xacro:macro>

</robot>
